CREATE TABLE [dbo].[AssetData]
(
[AssetId] [uniqueidentifier] NOT NULL,
[Year] [int] NOT NULL,
[IsMostRecent] [bit] NOT NULL,
[TextField0] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField1] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField2] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField3] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField4] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField5] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField6] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField7] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField8] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField9] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField10] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField11] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField12] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField13] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField14] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField15] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField16] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField17] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField18] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField19] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField20] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField21] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField22] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField23] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField24] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField25] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField26] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField27] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField28] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField29] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField30] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField31] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField32] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField33] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField34] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField35] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField36] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField37] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField38] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField39] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField40] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField41] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField42] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField43] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField44] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField45] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField46] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField47] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField48] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField49] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField50] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField51] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField52] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField53] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField54] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField55] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField56] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField57] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField58] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField59] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField60] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField61] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField62] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField63] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField64] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField65] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField66] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField67] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField68] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField69] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField70] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField71] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField72] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField73] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField74] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField75] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField76] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField77] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField78] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField79] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField80] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField81] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField82] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField83] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField84] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField85] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField86] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField87] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField88] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField89] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField90] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField91] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField92] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField93] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField94] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField95] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField96] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField97] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField98] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField99] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumericField0] [numeric] (8, 2) NULL,
[NumericField1] [numeric] (8, 2) NULL,
[NumericField2] [numeric] (8, 2) NULL,
[NumericField3] [numeric] (8, 2) NULL,
[NumericField4] [numeric] (8, 2) NULL,
[NumericField5] [numeric] (8, 2) NULL,
[NumericField6] [numeric] (8, 2) NULL,
[NumericField7] [numeric] (8, 2) NULL,
[NumericField8] [numeric] (8, 2) NULL,
[NumericField9] [numeric] (8, 2) NULL,
[NumericField10] [numeric] (8, 2) NULL,
[NumericField11] [numeric] (8, 2) NULL,
[NumericField12] [numeric] (8, 2) NULL,
[NumericField13] [numeric] (8, 2) NULL,
[NumericField14] [numeric] (8, 2) NULL,
[NumericField15] [numeric] (8, 2) NULL,
[NumericField16] [numeric] (8, 2) NULL,
[NumericField17] [numeric] (8, 2) NULL,
[NumericField18] [numeric] (8, 2) NULL,
[NumericField19] [numeric] (8, 2) NULL,
[NumericField20] [numeric] (8, 2) NULL,
[NumericField21] [numeric] (8, 2) NULL,
[NumericField22] [numeric] (8, 2) NULL,
[NumericField23] [numeric] (8, 2) NULL,
[NumericField24] [numeric] (8, 2) NULL,
[NumericField25] [numeric] (8, 2) NULL,
[NumericField26] [numeric] (8, 2) NULL,
[NumericField27] [numeric] (8, 2) NULL,
[NumericField28] [numeric] (8, 2) NULL,
[NumericField29] [numeric] (8, 2) NULL,
[NumericField30] [numeric] (8, 2) NULL,
[NumericField31] [numeric] (8, 2) NULL,
[NumericField32] [numeric] (8, 2) NULL,
[NumericField33] [numeric] (8, 2) NULL,
[NumericField34] [numeric] (8, 2) NULL,
[NumericField35] [numeric] (8, 2) NULL,
[NumericField36] [numeric] (8, 2) NULL,
[NumericField37] [numeric] (8, 2) NULL,
[NumericField38] [numeric] (8, 2) NULL,
[NumericField39] [numeric] (8, 2) NULL,
[NumericField40] [numeric] (8, 2) NULL,
[NumericField41] [numeric] (8, 2) NULL,
[NumericField42] [numeric] (8, 2) NULL,
[NumericField43] [numeric] (8, 2) NULL,
[NumericField44] [numeric] (8, 2) NULL,
[NumericField45] [numeric] (8, 2) NULL,
[NumericField46] [numeric] (8, 2) NULL,
[NumericField47] [numeric] (8, 2) NULL,
[NumericField48] [numeric] (8, 2) NULL,
[NumericField49] [numeric] (8, 2) NULL,
[NumericField50] [numeric] (8, 2) NULL,
[NumericField51] [numeric] (8, 2) NULL,
[NumericField52] [numeric] (8, 2) NULL,
[NumericField53] [numeric] (8, 2) NULL,
[NumericField54] [numeric] (8, 2) NULL,
[NumericField55] [numeric] (8, 2) NULL,
[NumericField56] [numeric] (8, 2) NULL,
[NumericField57] [numeric] (8, 2) NULL,
[NumericField58] [numeric] (8, 2) NULL,
[NumericField59] [numeric] (8, 2) NULL,
[NumericField60] [numeric] (8, 2) NULL,
[NumericField61] [numeric] (8, 2) NULL,
[NumericField62] [numeric] (8, 2) NULL,
[NumericField63] [numeric] (8, 2) NULL,
[NumericField64] [numeric] (8, 2) NULL,
[NumericField65] [numeric] (8, 2) NULL,
[NumericField66] [numeric] (8, 2) NULL,
[NumericField67] [numeric] (8, 2) NULL,
[NumericField68] [numeric] (8, 2) NULL,
[NumericField69] [numeric] (8, 2) NULL,
[NumericField70] [numeric] (8, 2) NULL,
[NumericField71] [numeric] (8, 2) NULL,
[NumericField72] [numeric] (8, 2) NULL,
[NumericField73] [numeric] (8, 2) NULL,
[NumericField74] [numeric] (8, 2) NULL,
[NumericField75] [numeric] (8, 2) NULL,
[NumericField76] [numeric] (8, 2) NULL,
[NumericField77] [numeric] (8, 2) NULL,
[NumericField78] [numeric] (8, 2) NULL,
[NumericField79] [numeric] (8, 2) NULL,
[NumericField80] [numeric] (8, 2) NULL,
[NumericField81] [numeric] (8, 2) NULL,
[NumericField82] [numeric] (8, 2) NULL,
[NumericField83] [numeric] (8, 2) NULL,
[NumericField84] [numeric] (8, 2) NULL,
[NumericField85] [numeric] (8, 2) NULL,
[NumericField86] [numeric] (8, 2) NULL,
[NumericField87] [numeric] (8, 2) NULL,
[NumericField88] [numeric] (8, 2) NULL,
[NumericField89] [numeric] (8, 2) NULL,
[NumericField90] [numeric] (8, 2) NULL,
[NumericField91] [numeric] (8, 2) NULL,
[NumericField92] [numeric] (8, 2) NULL,
[NumericField93] [numeric] (8, 2) NULL,
[NumericField94] [numeric] (8, 2) NULL,
[NumericField95] [numeric] (8, 2) NULL,
[NumericField96] [numeric] (8, 2) NULL,
[NumericField97] [numeric] (8, 2) NULL,
[NumericField98] [numeric] (8, 2) NULL,
[NumericField99] [numeric] (8, 2) NULL,
[TextField100] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField101] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField102] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField103] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField104] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField105] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField106] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField107] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField108] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField109] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField110] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField111] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField112] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField113] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField114] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField115] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField116] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField117] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField118] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField119] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField120] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField121] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField122] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField123] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField124] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField125] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField126] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField127] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField128] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField129] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField130] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField131] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField132] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField133] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField134] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField135] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField136] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField137] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField138] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField139] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField140] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField141] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField142] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField143] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField144] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField145] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField146] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField147] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField148] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TextField149] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [nvarchar] (2048) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BigNumericField0] [numeric] (12, 4) NULL,
[BigNumericField1] [numeric] (12, 4) NULL,
[BigNumericField2] [numeric] (12, 4) NULL,
[BigNumericField3] [numeric] (13, 4) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AssetData] ADD CONSTRAINT [PK_AssetData_1] PRIMARY KEY NONCLUSTERED ([AssetId], [Year]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AssetData] ADD CONSTRAINT [FK_AssetData_Asset] FOREIGN KEY ([AssetId]) REFERENCES [dbo].[Asset] ([Id])
GO
EXEC sp_addextendedproperty N'MS_Description', N'Deprecated Silverlight. It was used for LTBP project to improve performance of some key attribute field querying', 'SCHEMA', N'dbo', 'TABLE', N'AssetData', NULL, NULL
GO
